{{- if .Values.enabled }}
{{- if .Values.rest }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-rest-nginx-conf
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
data:
  nginx.conf: |-
{{ .Files.Get "config/nginx.conf" | nindent 4 }}
{{- end }}
{{- end }}
