REMOTE_URL:
- file:///opt/spaceone/file-manager/config/database.yaml
- file:///opt/spaceone/file-manager/config/shared.yaml
- file:///opt/spaceone/file-manager/config/application.yaml
GLOBAL:
  MAX_WORKERS: 1000
  DATABASES:
    default:
      db: file-manager
      host: mongodb
      port: 27017
      maxPoolSize: 200
      username: secret_user
      password: secret_password
  CACHES:
    default:
      backend: spaceone.core.cache.redis_cache.RedisCache
      host: redis
      port: 6379
      db: 1
      encoding: utf-8
      socket_timeout: 10
      socket_connect_timeout: 10
  LOG:
    loggers:
      spaceone:
        handlers:
          - console
          - file
    handlers:
      file:
        type: file
        filename: /var/log/spaceone/file_manager.log
  HANDLERS:
    authentication:
    - backend: spaceone.core.handler.authentication_handler.AuthenticationGRPCHandler
      uri: grpc://identity:50051/v1/Domain/get_public_key
    authorization:
    - backend: spaceone.core.handler.authorization_handler.AuthorizationGRPCHandler
      uri: grpc://identity:50051/v1/Authorization/verify
    mutation:
    - backend: spaceone.core.handler.mutation_handler.SpaceONEMutationHandler
