name: "[Dispatch] Create Branch"

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: enter branch (release-x.y)
        required: true
        default: 'release-1.0'

jobs:
  create_branch:
    runs-on: ubuntu-latest
    steps:
      - name: create branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          branch: '${{ github.event.inputs.branch_name }}'
